#define TMUX     LCTL(KC_A)
#define CTL_ESC  CTL_T(KC_ESC)
#define SYM_A    LT(SYMBOL, KC_A)
#define ALT_S    ALT_T(KC_S)
#define CTL_KT   CTL_T(KC_T)
#define NUM_Z    LT(NUM, KC_Z)
#define GUI_R    GUI_T(KC_R)
#define LT_NAV   LT(NAV, LCTL(KC_A))
#define GUI_SLSH GUI_T(KC_SLSH)

#define CTL_N    RCTL_T(KC_N)
#define ALT_E    RALT_T(KC_E)
#define GUI_I    RGUI_T(KC_I)
#define SYM_O    LT(SYMBOL, KC_O)
#define NUM_SLSH LT(NUM, KC_SLSH)
#define GUI_MINS GUI_T(KC_MINS)
// Mac shortcuts
#define NEXT     RGUI(KC_TAB)
#define DESK_L   LCTL(KC_LEFT)
#define DESK_R   LCTL(KC_RIGHT)
#define HOME     RGUI(KC_LEFT)
#define END      RGUI(KC_RIGHT)
#define TOP      RGUI(KC_UP)
